### PR TITLE
fix: add indicator on scroll when messages out of view

### LINKED ISSUE #308: Have some kind of indicator that there is more content below the fold when there is more content.
We don't, yet, have the component to show from @aubrey-oneal but lets assume its one of these https://web-components.carbondesignsystem.com/?path=/docs/experimental-chat-button--overview for this writeup.

https://github.com/carbon-design-system/carbon-ai-chat/issues/307 is a pre-req for this issue.

The logic for this all will take place in https://github.com/carbon-design-system/carbon-ai-chat/blob/main/packages/ai-chat/src/chat/shared/containers/MessagesComponent.tsx. There is already a ref to `this.messagesContainerWithScrollingRef.current` to make use of.

*Notes*
- We don't need this indicator to show up if they are *almost* to the bottom of the page, only if there is a "significant" more amount of content. For instance, we don't want this button to be showing up when they are 1px away from being from the bottom of the content hiding the content they actually want to see. This might be just something we design live with @aubrey-oneal rather than get specs in advance.
- We need to throttle the scroll listener, obviously, for performance and also to avoid the button flashing in and out during auto scrolling. We can't debounce because then we won't get the button to show until auto scrolling has completed, which defeats the purpose. We should make sure we call lodash throttle with `leading: true, trailing: true` to get an initial and final call.

*Requirements*
- If there are more than X pixels left from the current scroll position to the bottom of the content, show the button (likely with z-index to hover above the content).
- This should work while either auto scrolling or manually scrolling.
- Watch for re-sizes of the chat, not just scrolling! There is already a resize observer, to make use of. 307 may make this task free.
- We need to make sure that in small views like the sidebar view the indicator can nicely fit. Its possible that we will need an alternate icon only version of the indicator on very small view sizes.

### PR DESCRIPTION
**Pull request by UzairJ99**
Closes #308 

Requirements:

- If there are more than X pixels left from the current scroll position to the bottom of the content, show the button (likely with z-index to hover above the content).
- This should work while either auto scrolling or manually scrolling.
- Watch for re-sizes of the chat, not just scrolling! There is already a resize observer, to make use of. 307 may make this task free.
- We need to make sure that in small views like the sidebar view the indicator can nicely fit. Its possible that we will need an alternate icon only version of the indicator on very small view sizes.

#### Changelog

**New**

- Temporary down arrow icon for the indicator (until the confirmed design is given from the designers) above the chat messages
- Only appears when the user is X pixels away from the bottom of the chat
- Appears when streaming and the scrollbar is still above the bottom as well as when the user scrolls manually away from the bottom of the chat
- Icon fits in all views nicely - may have to revisit this with the updated design if things change later
- Issue resolution works both with and without the resolution of issue #307 
- Clicking on the indicator button will scroll down to the bottom of the chat through doAutoScroll with options set to {scrollToBottom: 0}

**Changed**

- state is updated with { scrollDown: shouldRender } if the scrollbar is above the threshold X value from the bottom of the chat
- shouldRender determins if the icon should be rendered based on above mentioned threshold value

#### Testing / Reviewing

1. stream messages or code from the options and do not scroll yourself yet (to see its effect)
2. the icon should appear once the scrollbar automatically adjusts itself due to the messages rendering below the visible messages container
3. scroll however you like, the icon will appear whenever you're not at/close-to the bottom
4. clicking on the button will take you to the bottom of the messages container

### CODE REVIEW

File: packages/ai-chat/src/chat/shared/containers/MessagesComponent.tsx [hunk 1]
```diff
@@ -959,6 +999,13 @@ class MessagesComponent extends PureComponent<MessagesProps, MessagesState> {
               notifications={notifications}
             />
             {this.renderScrollHandle(false)}
+            {unreadMessages && (
+              <div className="WAC__messages--unreadMessagesIndicator">
+                <div className="WAC__messages--unreadMessagesIndicatorIcon">
+                  <ArrowDown />
```
Comment (ethanwinters) [inline packages/ai-chat/src/chat/shared/containers/MessagesComponent.tsx:1005]: Should this be a scroll to bottom button?

File: packages/ai-chat/src/chat/shared/containers/MessagesComponent.scss [hunk 2]
```diff
@@ -56,3 +57,21 @@
   block-size: 100%;
   inline-size: 100%;
 }
+
+.WAC__messages--unreadMessagesIndicator {
```
Comment (ethanwinters) [inline packages/ai-chat/src/chat/shared/containers/MessagesComponent.scss:61]: We actually have an "unread messages indicator" on the launcher to show you have received messages while you have it minimized. Just to avoid confusion can you make up a different name here?

**Review by ethanwinters — COMMENTED** [review]
I'm out next week so just left a couple of comments.

**Review by ChengTing315 — APPROVED** [review]

**Review by OikuraHoro — APPROVED** [review]
